upstream_package_name: rhc
downstream_package_name: rhc
specfile_path: rhc.spec

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - make
  - 'pkgconfig(dbus-1)'
  - 'pkgconfig(systemd)'
  - rpm-build

actions:
  post-upstream-clone:
    - bash -c "mkdir out"
    - bash -c "make -f .copr/Makefile srpm outdir=./out"
    - bash -c "ls -la ./out"
  get-current-version:
    - bash -c "awk '/^Version:/ {print $2;}' ./rhc.spec"
  create-archive:
    - bash -c 'echo out/rhc-*.tar.*'
  fix-spec-file:
    - echo 'nothing to fix'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9